config:
  rsocket:
    port: 8888
    delay: 100
    socket_timeout: 13
    capt_timeout: 10
    solve_timeout: 10
    recipe_timeout: 10
    protocol: motoman
#    update_frame_id: the frame r_socket.js will update, the alternative of ROS driver

